#!/bin/sh
set -eu

: "${MINIPBX_WEB_HOST:=0.0.0.0}"
: "${MINIPBX_WEB_PORT:=8080}"
: "${ASTERISK_RTP_START:=10000}"
: "${ASTERISK_RTP_END:=10100}"
: "${MINIPBX_RUNTIME_USER:=asterisk}"

mkdir -p /var/lib/minipbx/generated /var/lib/minipbx/backups /var/lib/minipbx/imports /var/lib/minipbx/prompts /var/log/asterisk/cdr-csv /var/spool/asterisk /var/run/asterisk /var/lib/asterisk /etc/asterisk

run_as_runtime_user() {
  if [ "$(id -u)" -eq 0 ]; then
    uid="$(id -u "$MINIPBX_RUNTIME_USER")"
    gid="$(id -g "$MINIPBX_RUNTIME_USER")"
    setpriv --reuid "$uid" --regid "$gid" --init-groups "$@"
  else
    "$@"
  fi
}

create_if_missing() {
  file="$1"
  content="$2"
  if [ ! -f "$file" ]; then
    printf '%s\n' "$content" > "$file"
  fi
}

write_config() {
  file="$1"
  content="$2"
  printf '%s\n' "$content" > "$file"
}

ensure_include() {
  file="$1"
  include="$2"
  touch "$file"
  if ! grep -q "$include" "$file"; then
    printf '\n#include %s\n' "$include" >> "$file"
  fi
}

create_if_missing /etc/asterisk/pjsip_minipbx.conf "; Generated by MiniPBX. Empty until first configuration apply."
create_if_missing /etc/asterisk/extensions_minipbx.conf "; Generated by MiniPBX. Empty until first configuration apply."
create_if_missing /etc/asterisk/voicemail_minipbx.conf "; Generated by MiniPBX. Empty until first configuration apply."
create_if_missing /etc/asterisk/manager_minipbx.conf "; Generated by MiniPBX. Empty until first configuration apply."

cat >/etc/asterisk/asterisk.conf <<'EOF'
; Managed by MiniPBX container entrypoint.
; Keep Asterisk built-in directory defaults so Debian/Ubuntu multi-arch
; module paths continue to work inside the container.

[options]
documentation_language = en_US
EOF

cat >/etc/asterisk/modules.conf <<'EOF'
; Managed by MiniPBX container entrypoint.
; Minimal module set for MiniPBX: PJSIP, file dialplan, voicemail, RTP,
; playback, bridging, CDR CSV and AMI helper modules.

[modules]
autoload=no

load => app_dial.so
load => app_exec.so
load => app_playback.so
load => app_stack.so
load => app_verbose.so
load => app_voicemail.so
load => app_waituntil.so

load => bridge_builtin_features.so
load => bridge_builtin_interval_features.so
load => bridge_holding.so
load => bridge_native_rtp.so
load => bridge_simple.so
load => bridge_softmix.so

load => cdr_csv.so
load => chan_pjsip.so

load => codec_gsm.so
load => codec_resample.so
load => codec_ulaw.so
load => codec_alaw.so
load => codec_g722.so

load => format_gsm.so
load => format_pcm.so
load => format_wav_gsm.so
load => format_wav.so

load => func_callerid.so
load => func_cdr.so
load => func_pjsip_endpoint.so
load => func_sorcery.so
load => func_devstate.so
load => func_strings.so
load => func_timeout.so

load => pbx_config.so

load => res_pjproject.so
load => res_pjsip_acl.so
load => res_pjsip_authenticator_digest.so
load => res_pjsip_caller_id.so
load => res_pjsip_dialog_info_body_generator.so
load => res_pjsip_diversion.so
load => res_pjsip_dtmf_info.so
load => res_pjsip_endpoint_identifier_anonymous.so
load => res_pjsip_endpoint_identifier_ip.so
load => res_pjsip_endpoint_identifier_user.so
load => res_pjsip_exten_state.so
load => res_pjsip_header_funcs.so
load => res_pjsip_logger.so
load => res_pjsip_messaging.so
load => res_pjsip_mwi_body_generator.so
load => res_pjsip_mwi.so
load => res_pjsip_nat.so
load => res_pjsip_one_touch_record_info.so
load => res_pjsip_outbound_authenticator_digest.so
load => res_pjsip_outbound_publish.so
load => res_pjsip_outbound_registration.so
load => res_pjsip_path.so
load => res_pjsip_pidf_body_generator.so
load => res_pjsip_pidf_digium_body_supplement.so
load => res_pjsip_pidf_eyebeam_body_supplement.so
load => res_pjsip_publish_asterisk.so
load => res_pjsip_pubsub.so
load => res_pjsip_refer.so
load => res_pjsip_registrar.so
load => res_pjsip_rfc3326.so
load => res_pjsip_sdp_rtp.so
load => res_pjsip_send_to_voicemail.so
load => res_pjsip_session.so
load => res_pjsip.so
load => res_pjsip_t38.so
load => res_pjsip_xpidf_body_generator.so
load => res_rtp_asterisk.so
load => res_sorcery_astdb.so
load => res_sorcery_config.so
load => res_sorcery_memory.so
load => res_sorcery_realtime.so
load => res_timing_timerfd.so
load => res_manager_devicestate.so
load => res_manager_presencestate.so
EOF

ensure_include /etc/asterisk/pjsip.conf pjsip_minipbx.conf
ensure_include /etc/asterisk/extensions.conf extensions_minipbx.conf
ensure_include /etc/asterisk/voicemail.conf voicemail_minipbx.conf
ensure_include /etc/asterisk/manager.conf manager_minipbx.conf

cat >/etc/asterisk/rtp.conf <<EOF
[general]
rtpstart=${ASTERISK_RTP_START}
rtpend=${ASTERISK_RTP_END}
EOF

write_config /etc/asterisk/udptl.conf "[general]"
write_config /etc/asterisk/acl.conf "; Managed by MiniPBX container entrypoint."
write_config /etc/asterisk/features.conf "[general]

[featuremap]

[applicationmap]"
write_config /etc/asterisk/cel.conf "[general]
enable=no"
write_config /etc/asterisk/pjproject.conf "[startup]"
write_config /etc/asterisk/ccss.conf "[general]"
write_config /etc/asterisk/indications.conf "[general]
country=fr

[fr]
description=France
ringcadence=1500,3500
dial=440
busy=440/500,0/500
ring=440/1500,0/3500
congestion=440/250,0/250
callwaiting=440/300,0/10000
dialrecall=440
record=1400/500,0/15000
info=950/330,1400/330,1800/330,0
stutter=440+330"
write_config /etc/asterisk/musiconhold.conf "[general]"
write_config /etc/asterisk/stasis.conf "[declined_message_types]"
write_config /etc/asterisk/logger.conf "[logfiles]
console => notice,warning,error"
write_config /etc/asterisk/cdr.conf "[general]
enable=yes

[csv]
loguniqueid=yes
loguserfield=yes"

if [ "$(id -u)" -eq 0 ]; then
  chown -R "$MINIPBX_RUNTIME_USER:$MINIPBX_RUNTIME_USER" \
    /var/lib/minipbx \
    /var/log/asterisk \
    /var/spool/asterisk \
    /var/run/asterisk \
    /var/lib/asterisk \
    /etc/asterisk
fi

run_as_runtime_user python -m app.startup_config
export MINIPBX_DATABASE_INITIALIZED=true

run_as_runtime_user asterisk -C /etc/asterisk/asterisk.conf -f &
ASTERISK_PID="$!"

sleep 2
if ! kill -0 "$ASTERISK_PID" 2>/dev/null; then
  echo "Asterisk failed to start." >&2
  wait "$ASTERISK_PID" 2>/dev/null || true
  exit 1
fi

run_as_runtime_user uvicorn app.main:app --host "$MINIPBX_WEB_HOST" --port "$MINIPBX_WEB_PORT" &
WEB_PID="$!"

term_handler() {
  kill "$WEB_PID" "$ASTERISK_PID" 2>/dev/null || true
  wait "$WEB_PID" "$ASTERISK_PID" 2>/dev/null || true
}
trap term_handler INT TERM

wait "$WEB_PID"
